In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Setup Successful")

Setup Successful

In [2]:
import os

os.chdir(r"D:\Supply_Chain_Analytics_Project")

print(os.getcwd())

D:\Supply_Chain_Analytics_Project

In [3]:
import os
print(os.getcwd())

D:\Supply_Chain_Analytics_Project

In [4]:
import os
print(os.listdir())

['APP', 'DATA', 'DOCS', 'MODELS', 'NOTEBOOKS', 'OUTPUTS']

In [5]:
import os

print(os.listdir("DATA"))

['CLEANED', 'PROCESSED', 'RAW']

In [6]:
print(os.listdir("DATA/RAW"))

['Customer.csv', 'Employee.csv', 'OrderDetails.csv', 'Orders.csv', 'Product.csv', 'Region.csv', 'Warehouse.csv']

In [7]:
import pandas as pd

customer = pd.read_csv("DATA/RAW/Customer.csv")

customer.head()

,CustomerID,CustomerName,CustomerEmail,CustomerPhone,CustomerAddress,CustomerCreditLimit
0,2301,Flor Stone,flor.stone@raytheon.com,1.317123e+10,2904 S Salina St,5000
1,2302,Lavera Emerson,lavera.emerson@plainsallamerican.com,1.317123e+10,"5344 Haverford Ave, Philadelphia",5000
2,2303,Fern Head,fern.head@usfoods.com,1.812123e+10,"1795 Wu Meng, Muang Chonburi",1200
3,2304,Shyla Ortiz,shyla.ortiz@abbvie.com,1.317123e+10,"Walpurgisstr 69, Munich",2400
4,2305,Jeni Levy,jeni.levy@centene.com,1.812121e+10,"Via Frenzy 6903, Roma",1200

In [8]:
customer.info()
customer.shape
customer.columns
customer.describe(include="all")
customer.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CustomerID           400 non-null    int64
 1   CustomerName         400 non-null    object
 2   CustomerEmail        400 non-null    object
 3   CustomerPhone        400 non-null    float64
 4   CustomerAddress      400 non-null    object
 5   CustomerCreditLimit  400 non-null    int64
dtypes: float64(1), int64(2), object(3)
memory usage: 18.9+ KB

CustomerID             0
CustomerName           0
CustomerEmail          0
CustomerPhone          0
CustomerAddress        0
CustomerCreditLimit    0
dtype: int64

In [9]:
import pandas as pd

customer = pd.read_csv("DATA/RAW/Employee.csv")

customer.head()

,EmployeeID,EmployeeName,EmployeeEmail,EmployeePhone,EmployeeHireDate,EmployeeJobTitle,WarehouseID
0,6309,Summer Payne,summer.payne@example.com,5.151238e+09,2016/06/07,Public Accountant,101
1,6310,Rose Stephens,rose.stephens@example.com,5.151238e+09,2016/06/07,Accounting Manager,102
2,6311,Annabelle Dunn,annabelle.dunn@example.com,5.151234e+09,2016/09/17,Administration Assistant,103
3,6312,Tommy Bailey,tommy.bailey@example.com,5.151235e+09,2016/06/17,President,104
4,6313,Blake Cooper,blake.cooper@example.com,5.151235e+09,2016/01/13,Administration Vice President,105

In [10]:
customer.info()
customer.shape
customer.columns
customer.describe(include="all")
customer.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        400 non-null    int64
 1   EmployeeName      400 non-null    object
 2   EmployeeEmail     400 non-null    object
 3   EmployeePhone     400 non-null    float64
 4   EmployeeHireDate  400 non-null    object
 5   EmployeeJobTitle  400 non-null    object
 6   WarehouseID       400 non-null    int64
dtypes: float64(1), int64(2), object(4)
memory usage: 22.0+ KB

EmployeeID          0
EmployeeName        0
EmployeeEmail       0
EmployeePhone       0
EmployeeHireDate    0
EmployeeJobTitle    0
WarehouseID         0
dtype: int64

In [12]:
import pandas as pd

customer = pd.read_csv("DATA/RAW/Orders.csv")

customer.head()

   OrderID   OrderDate  CustomerID
0     7272  2016/11/17        2301
1     7273  2017/02/20        2302
2     7274  2017/01/03        2303
3     7275  2017/10/15        2304
4     7276  2017/04/09        2305

In [13]:
customer.info()
customer.shape
customer.columns
customer.describe(include="all")
customer.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     400 non-null    int64
 1   OrderDate   400 non-null    object
 2   CustomerID  400 non-null    int64
dtypes: int64(2), object(1)
memory usage: 9.5+ KB

OrderID       0
OrderDate     0
CustomerID    0
dtype: int64

In [14]:
import pandas as pd

customer = pd.read_csv("DATA/RAW/OrderDetails.csv")

customer.head()

,OrderDetailsID,ProductID,OrderItemQuantity,PerUnitPrice,OrderStatus,OrderID
0,1,P001,132,469.99,Shipped,7272
1,2,P002,124,519.99,Shipped,7273
2,3,P003,92,800.74,Canceled,7274
3,4,P004,128,849.99,Pending,7275
4,5,P005,106,109.99,Shipped,7276

In [15]:
customer.info()
customer.shape
customer.columns
customer.describe(include="all")
customer.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OrderDetailsID     400 non-null    int64
 1   ProductID          400 non-null    object
 2   OrderItemQuantity  400 non-null    int64
 3   PerUnitPrice       400 non-null    float64
 4   OrderStatus        400 non-null    object
 5   OrderID            400 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 18.9+ KB

OrderDetailsID       0
ProductID            0
OrderItemQuantity    0
PerUnitPrice         0
OrderStatus          0
OrderID              0
dtype: int64

In [16]:
import pandas as pd

customer = pd.read_csv("DATA/RAW/Product.csv")

customer.head()

,ProductID,ProductName,CategoryName,ProductDescription,ProductStandardCost,ProductListPrice,Profit
0,P001,Intel Xeon E5-2699 V3 (OEM/Tray),CPU,"Speed:2.3GHz,Cores:18,TDP:145W",2867.51,3410.46,542.95
1,P002,Intel Xeon E5-2697 V3,CPU,"Speed:2.6GHz,Cores:14",2326.27,2774.98,448.71
2,P003,Intel Xeon E5-2698 V3 (OEM/Tray),CPU,Speed:2.3GHz,2035.18,2660.72,625.54
3,P004,Intel Xeon E5-2697 V4,CPU,"Cores:18,TDP:145W",2144.40,2554.99,410.59
4,P005,Intel Xeon E5-2685 V3 (OEM/Tray),CPU,"Speed:2.6GHz,Cores:12",2012.11,2501.69,489.58

In [17]:
customer.info()
customer.shape
customer.columns
customer.describe(include="all")
customer.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ProductID            400 non-null    object
 1   ProductName          400 non-null    object
 2   CategoryName         400 non-null    object
 3   ProductDescription   400 non-null    object
 4   ProductStandardCost  400 non-null    float64
 5   ProductListPrice     400 non-null    float64
 6   Profit               400 non-null    float64
dtypes: float64(3), object(4)
memory usage: 22.0+ KB

ProductID              0
ProductName            0
CategoryName           0
ProductDescription     0
ProductStandardCost    0
ProductListPrice       0
Profit                 0
dtype: int64

In [18]:
import pandas as pd

customer = pd.read_csv("DATA/RAW/Region.csv")

customer.head()

,RegionID,RegionName,CountryName,State,City,PostalCode
0,1,South America,United States of America,Texas,Southlake,26192
1,2,South America,United States of America,Texas,Southlake,26192
2,3,South America,United States of America,Texas,Southlake,26192
3,4,South America,United States of America,Texas,Southlake,26192
4,5,South America,United States of America,Texas,Southlake,26192

In [19]:
customer.info()
customer.shape
customer.columns
customer.describe(include="all")
customer.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RegionID     400 non-null    int64
 1   RegionName   400 non-null    object
 2   CountryName  400 non-null    object
 3   State        400 non-null    object
 4   City         400 non-null    object
 5   PostalCode   400 non-null    object
dtypes: int64(1), object(5)
memory usage: 18.9+ KB

RegionID       0
RegionName     0
CountryName    0
State          0
City           0
PostalCode     0
dtype: int64

In [20]:
import pandas as pd

customer = pd.read_csv("DATA/RAW/Warehouse.csv")

customer.head()

   WarehouseID    WarehouseName     WarehouseAddress  RegionID
0          101  Southlake Texas  2014 Jabberwocky Rd         1
1          102  Southlake Texas  2014 Jabberwocky Rd         2
2          103  Southlake Texas  2014 Jabberwocky Rd         3
3          104  Southlake Texas  2014 Jabberwocky Rd         4
4          105  Southlake Texas  2014 Jabberwocky Rd         5

In [21]:
customer.info()
customer.shape
customer.columns
customer.describe(include="all")
customer.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   WarehouseID       400 non-null    int64
 1   WarehouseName     400 non-null    object
 2   WarehouseAddress  400 non-null    object
 3   RegionID          400 non-null    int64
dtypes: int64(2), object(2)
memory usage: 12.6+ KB

WarehouseID         0
WarehouseName       0
WarehouseAddress    0
RegionID            0
dtype: int64