In [33]:
import pandas as pd

In [34]:
customer = pd.read_csv("DATA/RAW/Customer.csv")
employee = pd.read_csv("DATA/RAW/Employee.csv")
orders = pd.read_csv("DATA/RAW/Orders.csv")
orderdetails = pd.read_csv("DATA/RAW/OrderDetails.csv")
product = pd.read_csv("DATA/RAW/Product.csv")
warehouse = pd.read_csv("DATA/RAW/Warehouse.csv")
region = pd.read_csv("DATA/RAW/Region.csv")

In [35]:
print("Customer Columns:")
print(customer.columns)

print("\nEmployee Columns:")
print(employee.columns)

print("\nOrders Columns:")
print(orders.columns)

print("\nOrderDetails Columns:")
print(orderdetails.columns)

print("\nProduct Columns:")
print(product.columns)

print("\nWarehouse Columns:")
print(warehouse.columns)

print("\nRegion Columns:")
print(region.columns)

Customer Columns:
Index(['CustomerID', 'CustomerName', 'CustomerEmail', 'CustomerPhone',
       'CustomerAddress', 'CustomerCreditLimit'],
      dtype='object')

Employee Columns:
Index(['EmployeeID', 'EmployeeName', 'EmployeeEmail', 'EmployeePhone',
       'EmployeeHireDate', 'EmployeeJobTitle', 'WarehouseID'],
      dtype='object')

Orders Columns:
Index(['OrderID', 'OrderDate', 'CustomerID'], dtype='object')

OrderDetails Columns:
Index(['OrderDetailsID', 'ProductID', 'OrderItemQuantity', 'PerUnitPrice',
       'OrderStatus', 'OrderID'],
      dtype='object')

Product Columns:
Index(['ProductID', 'ProductName', 'CategoryName', 'ProductDescription',
       'ProductStandardCost', 'ProductListPrice', 'Profit'],
      dtype='object')

Warehouse Columns:
Index(['WarehouseID', 'WarehouseName', 'WarehouseAddress', 'RegionID'], dtype='object')

Region Columns:
Index(['RegionID', 'RegionName', 'CountryName', 'State', 'City', 'PostalCode'], dtype='object')

# Dataset Description

## Customer.csv
Purpose:
Stores customer information such as Customer ID, Name, Address, Phone Number, etc.

---

## Employee.csv
Purpose:
Stores employee details who handle customer orders.

---

## Orders.csv
Purpose:
Stores order information such as Order ID, Customer ID, Order Date, Warehouse ID, etc.

---

## OrderDetails.csv
Purpose:
Stores product details for each order such as Product ID, Quantity and Price.

---

## Product.csv
Purpose:
Stores product information such as Product ID, Product Name, Category and Price.

---

## Warehouse.csv
Purpose:
Stores warehouse information where products are stored.

---

## Region.csv
Purpose:
Stores region information for warehouses.

In [36]:
customer.head()

,CustomerID,CustomerName,CustomerEmail,CustomerPhone,CustomerAddress,CustomerCreditLimit
0,2301,Flor Stone,flor.stone@raytheon.com,1.317123e+10,2904 S Salina St,5000
1,2302,Lavera Emerson,lavera.emerson@plainsallamerican.com,1.317123e+10,"5344 Haverford Ave, Philadelphia",5000
2,2303,Fern Head,fern.head@usfoods.com,1.812123e+10,"1795 Wu Meng, Muang Chonburi",1200
3,2304,Shyla Ortiz,shyla.ortiz@abbvie.com,1.317123e+10,"Walpurgisstr 69, Munich",2400
4,2305,Jeni Levy,jeni.levy@centene.com,1.812121e+10,"Via Frenzy 6903, Roma",1200

In [37]:
employee.head()

,EmployeeID,EmployeeName,EmployeeEmail,EmployeePhone,EmployeeHireDate,EmployeeJobTitle,WarehouseID
0,6309,Summer Payne,summer.payne@example.com,5.151238e+09,2016/06/07,Public Accountant,101
1,6310,Rose Stephens,rose.stephens@example.com,5.151238e+09,2016/06/07,Accounting Manager,102
2,6311,Annabelle Dunn,annabelle.dunn@example.com,5.151234e+09,2016/09/17,Administration Assistant,103
3,6312,Tommy Bailey,tommy.bailey@example.com,5.151235e+09,2016/06/17,President,104
4,6313,Blake Cooper,blake.cooper@example.com,5.151235e+09,2016/01/13,Administration Vice President,105

In [38]:
orders.head()

   OrderID   OrderDate  CustomerID
0     7272  2016/11/17        2301
1     7273  2017/02/20        2302
2     7274  2017/01/03        2303
3     7275  2017/10/15        2304
4     7276  2017/04/09        2305

In [39]:
orderdetails.head()

,OrderDetailsID,ProductID,OrderItemQuantity,PerUnitPrice,OrderStatus,OrderID
0,1,P001,132,469.99,Shipped,7272
1,2,P002,124,519.99,Shipped,7273
2,3,P003,92,800.74,Canceled,7274
3,4,P004,128,849.99,Pending,7275
4,5,P005,106,109.99,Shipped,7276

In [40]:
product.head()

,ProductID,ProductName,CategoryName,ProductDescription,ProductStandardCost,ProductListPrice,Profit
0,P001,Intel Xeon E5-2699 V3 (OEM/Tray),CPU,"Speed:2.3GHz,Cores:18,TDP:145W",2867.51,3410.46,542.95
1,P002,Intel Xeon E5-2697 V3,CPU,"Speed:2.6GHz,Cores:14",2326.27,2774.98,448.71
2,P003,Intel Xeon E5-2698 V3 (OEM/Tray),CPU,Speed:2.3GHz,2035.18,2660.72,625.54
3,P004,Intel Xeon E5-2697 V4,CPU,"Cores:18,TDP:145W",2144.40,2554.99,410.59
4,P005,Intel Xeon E5-2685 V3 (OEM/Tray),CPU,"Speed:2.6GHz,Cores:12",2012.11,2501.69,489.58

In [41]:
warehouse.head()

   WarehouseID    WarehouseName     WarehouseAddress  RegionID
0          101  Southlake Texas  2014 Jabberwocky Rd         1
1          102  Southlake Texas  2014 Jabberwocky Rd         2
2          103  Southlake Texas  2014 Jabberwocky Rd         3
3          104  Southlake Texas  2014 Jabberwocky Rd         4
4          105  Southlake Texas  2014 Jabberwocky Rd         5

In [42]:
region.head()

,RegionID,RegionName,CountryName,State,City,PostalCode
0,1,South America,United States of America,Texas,Southlake,26192
1,2,South America,United States of America,Texas,Southlake,26192
2,3,South America,United States of America,Texas,Southlake,26192
3,4,South America,United States of America,Texas,Southlake,26192
4,5,South America,United States of America,Texas,Southlake,26192

In [43]:
orders["CustomerID"].isin(customer["CustomerID"]).all()

np.True_

In [44]:
orderdetails["ProductID"].isin(product["ProductID"]).all()

np.True_

In [50]:

customer_orders = pd.merge(
    customer,
    orders,
    on="CustomerID"
)

customer_orders.head()

,CustomerID,CustomerName,CustomerEmail,CustomerPhone,CustomerAddress,CustomerCreditLimit,OrderID,OrderDate
0,2301,Flor Stone,flor.stone@raytheon.com,1.317123e+10,2904 S Salina St,5000,7272,2016/11/17
1,2302,Lavera Emerson,lavera.emerson@plainsallamerican.com,1.317123e+10,"5344 Haverford Ave, Philadelphia",5000,7273,2017/02/20
2,2303,Fern Head,fern.head@usfoods.com,1.812123e+10,"1795 Wu Meng, Muang Chonburi",1200,7274,2017/01/03
3,2304,Shyla Ortiz,shyla.ortiz@abbvie.com,1.317123e+10,"Walpurgisstr 69, Munich",2400,7275,2017/10/15
4,2305,Jeni Levy,jeni.levy@centene.com,1.812121e+10,"Via Frenzy 6903, Roma",1200,7276,2017/04/09

In [51]:
order_product = pd.merge(
    orderdetails,
    product,
    on="ProductID"
)

order_product.head()

,OrderDetailsID,ProductID,OrderItemQuantity,PerUnitPrice,OrderStatus,OrderID,ProductName,CategoryName,ProductDescription,ProductStandardCost,ProductListPrice,Profit
0,1,P001,132,469.99,Shipped,7272,Intel Xeon E5-2699 V3 (OEM/Tray),CPU,"Speed:2.3GHz,Cores:18,TDP:145W",2867.51,3410.46,542.95
1,2,P002,124,519.99,Shipped,7273,Intel Xeon E5-2697 V3,CPU,"Speed:2.6GHz,Cores:14",2326.27,2774.98,448.71
2,3,P003,92,800.74,Canceled,7274,Intel Xeon E5-2698 V3 (OEM/Tray),CPU,Speed:2.3GHz,2035.18,2660.72,625.54
3,4,P004,128,849.99,Pending,7275,Intel Xeon E5-2697 V4,CPU,"Cores:18,TDP:145W",2144.40,2554.99,410.59
4,5,P005,106,109.99,Shipped,7276,Intel Xeon E5-2685 V3 (OEM/Tray),CPU,"Speed:2.6GHz,Cores:12",2012.11,2501.69,489.58